language: minimal
dist: xenial
addons:
  ssh_known_hosts: 162.129.222.10
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libfftw3-dev
    - libgsl0-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - devscripts
    - axel
os:
- linux
- osx
osx_image: xcode9.4
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - CACHE_NAME="${TRAVIS_OS_NAME}-R-${TRAVIS_R_VERSION}"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} https://bit.ly/3eutpOa
- cat ${fname}; source ${fname}; rm ${fname}
#- install_all_sysdeps || true ;
- x=`export_clang_cxx`; eval ${x}
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; brew install -v freetype ; brew install axel ; fi
- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
- export cmake_version="3.14"
- cmake --version
- x=`cmake_setup`; echo "${x}"; eval ${x};
- cmake --version
- ls -lt /usr/local
#- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out /tmp/travis_rsa -d
#- eval "$(ssh-agent -s)"
#- chmod 600 /tmp/travis_rsa
#- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#- ssh-add /tmp/travis_rsa
#- travis_wait 100 sudo tar zcf /var/tmp/fsl-$TRAVIS_OS_NAME.tar.gz /usr/local/fsl
#- travis_wait 100 scp /var/tmp/fsl-$TRAVIS_OS_NAME.tar.gz igmadmin@162.129.222.10:/var/www/html/sites/default/files/sysdeps
#- travis_wait 100 wget -q https://neuroconductor.org/sites/default/files/sysdeps/fsl-$TRAVIS_OS_NAME.tar.gz -P /var/tmp
- travis_wait 100 axel -q -n 3 -o /var/tmp/ http://neuroconductor.org:8080/sites/default/files/sysdeps/fsl-$TRAVIS_OS_NAME.tar.gz 
- travis_wait 100 sudo tar -C / -xf /var/tmp/fsl-$TRAVIS_OS_NAME.tar.gz
- /usr/local/fsl/bin/flirt -version