language: minimal
dist: xenial
addons:
  ssh_known_hosts: neuroconductor.org
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libfftw3-dev
    - libgsl0-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - devscripts
os:
- linux
- osx
osx_image: xcode9.4
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - CACHE_NAME="${TRAVIS_OS_NAME}-R-${TRAVIS_R_VERSION}"
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} https://bit.ly/3eutpOa
- cat ${fname}; source ${fname}; rm ${fname}
- install_all_sysdeps || true ;
- x=`export_clang_cxx`; eval ${x}
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; brew install -v freetype ; fi
- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
- export cmake_version="3.14"
- cmake --version
- x=`cmake_setup`; echo "${x}"; eval ${x};
- cmake --version
- ls -lt /usr/local
- eval "$(ssh-agent -s)"
- chmod 600 ./travis_rsa
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./travis_rsa
- ssh -i ./travis_rsa igmadmin@neuroconductor pwd

