# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: minimal
dist: xenial
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libxml2-dev
      - libfftw3-dev
      - libgsl0-dev
      - mesa-common-dev
      - libglu1-mesa-dev
      - devscripts
os:
  - linux
  - osx
osx_image: xcode9.4
services: xvfb
env:
  global:
    - RGL_USE_NULL=TRUE
    - PROJECT_NAME=neuroconductor
    - DISPLAY=:99.0
    - CACHE_NAME="${TRAVIS_OS_NAME}-R-${TRAVIS_R_VERSION}"
before_install:
  - ulimit -n 2048
  - export PROJ_DIR=`basename $PWD`
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  - codename=`linux_codename`;
  - start_xvfb ;
  - x=`export_clang_cxx`; eval ${x}
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; brew install -v freetype ; fi
  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
  - clang_cxx
  - export cmake_version="3.11"
  - cmake --version
  - x=`cmake_setup`; echo "${x}"; eval ${x};
  - cmake --version
after_success: dump_logs
after_failure: dump_logs